name: Cleanup Build Artifacts

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for build artifacts
        run: |
          echo "Checking for build artifacts that should not be committed..."
          
          # Check for .wrangler/tmp files
          if find . -path "*/.wrangler/tmp/*" -type f 2>/dev/null | grep -q .; then
            echo "❌ Found .wrangler/tmp/ files that should not be committed:"
            find . -path "*/.wrangler/tmp/*" -type f 2>/dev/null | head -10
            echo "Please add .wrangler/tmp/ to .gitignore and remove these files."
            exit 1
          fi
          
          # Check for dist/ files
          if find . -name "dist" -type d 2>/dev/null | grep -q .; then
            echo "❌ Found dist/ directories that should not be committed:"
            find . -name "dist" -type d 2>/dev/null
            echo "Please add dist/ to .gitignore and remove these directories."
            exit 1
          fi
          
          # Check for build/ files
          if find . -name "build" -type d 2>/dev/null | grep -q .; then
            echo "❌ Found build/ directories that should not be committed:"
            find . -name "build" -type d 2>/dev/null
            echo "Please add build/ to .gitignore and remove these directories."
            exit 1
          fi
          
          # Check for TypeScript build info files
          if find . -name "*.tsbuildinfo" -type f 2>/dev/null | grep -q .; then
            echo "❌ Found .tsbuildinfo files that should not be committed:"
            find . -name "*.tsbuildinfo" -type f 2>/dev/null
            echo "Please add *.tsbuildinfo to .gitignore and remove these files."
            exit 1
          fi
          
          echo "✅ No build artifacts found. Repository is clean."

      - name: Check .gitignore patterns
        run: |
          echo "Verifying .gitignore contains required patterns..."
          
          required_patterns=(
            ".wrangler/tmp/"
            ".wrangler/state/"
            "dist/"
            "build/"
            "*.tsbuildinfo"
          )
          
          for pattern in "${required_patterns[@]}"; do
            if ! grep -q "^$pattern$" .gitignore; then
              echo "❌ Missing pattern in .gitignore: $pattern"
              exit 1
            fi
          done
          
          echo "✅ All required patterns found in .gitignore."
